/**
 * Lista central de cartões de ministérios/órgãos.
 *
 * No bloco "Grade de ministérios", escolha **Lista central (site)** para usar
 * este array em qualquer página (home, /ministerios, etc.) sem duplicar dados no CMS.
 *
 * Para popular: copie o JSON dos cartões da barra lateral do Volto (ou exporte do
 * Plone) e cole aqui como objetos neste array — mesma forma dos exemplos.
 * Opcional: sobrescreva em `applyConfig` com `config.settings.observatorioMinistryCardsSiteList = [...]`.
 *
 * Campos opcionais para busca/filtro no bloco (com “Busca e filtros” ativo):
 * - `themes` — temas separados por vírgula (ex.: economia, social) → opções do filtro por tema.
 * - `searchKeywords` — siglas e sinônimos (ex.: mds, mec) → ajudam na busca; não aparecem no cartão.
 */

export const ministryCardsSiteList = [
  {
    emoji: '⚖️',
    iconBgColor: '#e0e7ff',
    accentColor: '#3730a3',
    title: 'Advocacia-Geral da União',
    description:
      'Responsável pela representação jurídica da União e consultoria legal do governo federal.',
    highlightsLabel: 'Destaques',
    highlights: 'Defesa da União\nConsultoria jurídica\nPatrimônio público',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/agu/',
  },
  {
    emoji: '🏛️',
    iconBgColor: '#ede9fe',
    accentColor: '#6d28d9',
    title: 'Casa Civil',
    description:
      'Coordena as ações do governo e articula políticas entre ministérios.',
    highlightsLabel: 'Destaques',
    highlights:
      'Coordenação governamental\nPolíticas públicas\nRelações institucionais',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/casacivil/',
  },
  {
    emoji: '🔍',
    iconBgColor: '#fef3c7',
    accentColor: '#d97706',
    title: 'Controladoria-Geral da União',
    description:
      'Responsável por auditoria, transparência e combate à corrupção.',
    highlightsLabel: 'Destaques',
    highlights: 'Portal da Transparência\nAuditorias\nOuvidoria-Geral',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/cgu/',
  },
  {
    emoji: '🛡️',
    iconBgColor: '#e0f2fe',
    accentColor: '#0369a1',
    title: 'Gabinete de Segurança Institucional',
    description:
      'Atua na segurança institucional e assessoramento direto ao Presidente.',
    highlightsLabel: 'Destaques',
    highlights:
      'Segurança da informação\nGestão de crises\nProteção de autoridades',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/gsi/',
  },
  {
    emoji: '🌾',
    iconBgColor: '#dcfce7',
    accentColor: '#15803d',
    title: 'Ministério da Agricultura e Pecuária',
    description: 'Regula e fomenta o agronegócio brasileiro.',
    themes: 'economia, agro',
    searchKeywords: 'mapa, agricultura, pecuária, agronegócio',
    highlightsLabel: 'Destaques',
    highlights: 'Defesa agropecuária\nExportações\nProdução rural',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/agricultura/',
  },
  {
    emoji: '🔬',
    iconBgColor: '#e0f2fe',
    accentColor: '#0284c7',
    title: 'Ministério da Ciência, Tecnologia e Inovação',
    description: 'Promove ciência, pesquisa e inovação tecnológica.',
    highlightsLabel: 'Destaques',
    highlights: 'Pesquisa científica\nInovação\nTecnologia',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/mcti/',
  },
  {
    emoji: '🏙️',
    iconBgColor: '#f1f5f9',
    accentColor: '#334155',
    title: 'Ministério das Cidades',
    description: 'Responsável por políticas urbanas e habitação.',
    highlightsLabel: 'Destaques',
    highlights: 'Habitação\nMobilidade urbana\nSaneamento',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/cidades/',
  },
  {
    emoji: '📡',
    iconBgColor: '#eef2ff',
    accentColor: '#4338ca',
    title: 'Ministério das Comunicações',
    description: 'Regula telecomunicações e serviços de comunicação.',
    highlightsLabel: 'Destaques',
    highlights: 'Inclusão digital\nRadiodifusão\nInternet',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/mcom/',
  },
  {
    emoji: '🎭',
    iconBgColor: '#fce7f3',
    accentColor: '#be185d',
    title: 'Ministério da Cultura',
    description: 'Promove políticas culturais e incentivo às artes.',
    highlightsLabel: 'Destaques',
    highlights: 'Lei Rouanet\nPatrimônio cultural\nArtes',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/cultura/',
  },
  {
    emoji: '🪖',
    iconBgColor: '#e5e7eb',
    accentColor: '#374151',
    title: 'Ministério da Defesa',
    description: 'Coordena as Forças Armadas do Brasil.',
    highlightsLabel: 'Destaques',
    highlights: 'Exército\nMarinha\nAeronáutica',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/defesa/',
  },
  {
    emoji: '🤝',
    iconBgColor: '#fef9c3',
    accentColor: '#ca8a04',
    title: 'Ministério do Desenvolvimento e Assistência Social',
    description: 'Responsável por políticas sociais e combate à pobreza.',
    themes: 'social, desenvolvimento, assistência',
    searchKeywords: 'mds, bolsa família, cadastro único, assistência social',
    highlightsLabel: 'Destaques',
    highlights: 'Bolsa Família\nCadastro Único\nAssistência social',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/mds/',
  },
  {
    emoji: '🏭',
    iconBgColor: '#e0f7fa',
    accentColor: '#0f766e',
    title: 'Ministério do Desenvolvimento, Indústria, Comércio e Serviços',
    description: 'Fomenta indústria, comércio e serviços.',
    themes: 'economia, indústria, comércio',
    searchKeywords: 'mdic, indústria, comércio exterior',
    highlightsLabel: 'Destaques',
    highlights: 'Indústria\nComércio exterior\nServiços',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/mdic/',
  },
  {
    emoji: '⚖️',
    iconBgColor: '#f3e8ff',
    accentColor: '#7c3aed',
    title: 'Ministério dos Direitos Humanos e da Cidadania',
    description: 'Promove direitos humanos e cidadania.',
    themes: 'social, direitos humanos',
    searchKeywords: 'mdhc, mdh, direitos humanos',
    highlightsLabel: 'Destaques',
    highlights: 'Direitos civis\nInclusão\nProteção social',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/mdh/',
  },
  {
    emoji: '🎓',
    iconBgColor: '#dbeafe',
    accentColor: '#2563eb',
    title: 'Ministério da Educação',
    description:
      'Coordena a educação básica, superior e profissionalizante no país.',
    themes: 'social, educação',
    searchKeywords: 'mec, enem, fies, educação',
    highlightsLabel: 'Destaques',
    highlights: 'ENEM\nFIES\nLivro Didático',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/mec/',
  },
  {
    emoji: '💼',
    iconBgColor: '#ecfccb',
    accentColor: '#65a30d',
    title: 'Ministério do Empreendedorismo',
    description: 'Apoia micro e pequenas empresas.',
    themes: 'economia, empreendedorismo',
    searchKeywords: 'mei, microempresa, pequenos negócios',
    highlightsLabel: 'Destaques',
    highlights: 'MEI\nPequenos negócios\nIncentivo',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/memp/',
  },
  {
    emoji: '🏅',
    iconBgColor: '#fef3c7',
    accentColor: '#b45309',
    title: 'Ministério do Esporte',
    description: 'Promove políticas esportivas.',
    highlightsLabel: 'Destaques',
    highlights: 'Esporte de base\nAlto rendimento\nInclusão',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/esporte/',
  },
  {
    emoji: '💰',
    iconBgColor: '#dcfce7',
    accentColor: '#16a34a',
    title: 'Ministério da Fazenda',
    description: 'Gerencia finanças públicas e política econômica.',
    themes: 'economia, finanças',
    searchKeywords: 'fazenda, tesouro, receita federal, política fiscal',
    highlightsLabel: 'Destaques',
    highlights: 'Receita Federal\nTesouro Nacional\nPolítica fiscal',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/fazenda/',
  },
  {
    emoji: '⚙️',
    iconBgColor: '#e0f2fe',
    accentColor: '#0284c7',
    title: 'Ministério da Gestão e da Inovação',
    description: 'Moderniza a administração pública federal.',
    highlightsLabel: 'Destaques',
    highlights: 'Gov.br\nGestão pública\nTransformação digital',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/gestao/',
  },
  {
    emoji: '✊🏽',
    iconBgColor: '#fef3c7',
    accentColor: '#ca8a04',
    title: 'Ministério da Igualdade Racial',
    description: 'Promove igualdade racial e combate à discriminação.',
    highlightsLabel: 'Destaques',
    highlights: 'Políticas afirmativas\nInclusão\nCombate ao racismo',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/igualdaderacial/',
  },
  {
    emoji: '🌎',
    iconBgColor: '#e0f7fa',
    accentColor: '#0f766e',
    title: 'Ministério da Integração e Desenvolvimento Regional',
    description: 'Desenvolve regiões e reduz desigualdades.',
    highlightsLabel: 'Destaques',
    highlights: 'Defesa civil\nDesenvolvimento regional\nInfraestrutura',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/mdr/',
  },
  {
    emoji: '⚖️',
    iconBgColor: '#fee2e2',
    accentColor: '#dc2626',
    title: 'Ministério da Justiça e Segurança Pública',
    description: 'Cuida da segurança pública e do sistema de justiça.',
    highlightsLabel: 'Destaques',
    highlights: 'Polícia Federal\nSegurança pública\nCombate ao crime',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/mj/',
  },
  {
    emoji: '🌱',
    iconBgColor: '#dcfce7',
    accentColor: '#15803d',
    title: 'Ministério do Meio Ambiente',
    description: 'Protege o meio ambiente e promove sustentabilidade.',
    highlightsLabel: 'Destaques',
    highlights: 'Clima\nBiodiversidade\nSustentabilidade',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/mma/',
  },
  {
    emoji: '⛏️',
    iconBgColor: '#f1f5f9',
    accentColor: '#334155',
    title: 'Ministério de Minas e Energia',
    description: 'Gerencia recursos energéticos e minerais.',
    highlightsLabel: 'Destaques',
    highlights: 'Energia\nPetróleo e gás\nMineração',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/mme/',
  },
  {
    emoji: '👩',
    iconBgColor: '#fce7f3',
    accentColor: '#be185d',
    title: 'Ministério das Mulheres',
    description: 'Promove direitos das mulheres.',
    highlightsLabel: 'Destaques',
    highlights: 'Combate à violência\nIgualdade\nPolíticas públicas',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/mulheres/',
  },
  {
    emoji: '📊',
    iconBgColor: '#e0e7ff',
    accentColor: '#3730a3',
    title: 'Ministério do Planejamento e Orçamento',
    description: 'Coordena planejamento e orçamento federal.',
    highlightsLabel: 'Destaques',
    highlights: 'Orçamento\nPlanejamento\nPPA',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/planejamento/',
  },
  {
    emoji: '✈️',
    iconBgColor: '#e0f2fe',
    accentColor: '#0284c7',
    title: 'Ministério de Portos e Aeroportos',
    description: 'Administra infraestrutura portuária e aeroportuária.',
    highlightsLabel: 'Destaques',
    highlights: 'Portos\nAeroportos\nLogística',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/portos-e-aeroportos/',
  },
  {
    emoji: '🪶',
    iconBgColor: '#fef9c3',
    accentColor: '#a16207',
    title: 'Ministério dos Povos Indígenas',
    description: 'Defende os direitos dos povos indígenas.',
    highlightsLabel: 'Destaques',
    highlights: 'Terras indígenas\nCultura\nProteção',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/povosindigenas/',
  },
  {
    emoji: '👴',
    iconBgColor: '#e5e7eb',
    accentColor: '#374151',
    title: 'Ministério da Previdência Social',
    description: 'Gerencia benefícios previdenciários.',
    themes: 'social, previdência',
    searchKeywords: 'inss, aposentadoria, benefícios',
    highlightsLabel: 'Destaques',
    highlights: 'INSS\nAposentadoria\nBenefícios',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/previdencia/',
  },
  {
    emoji: '🌐',
    iconBgColor: '#e0f2fe',
    accentColor: '#0284c7',
    title: 'Ministério das Relações Exteriores',
    description: 'Responsável pela política externa do Brasil.',
    highlightsLabel: 'Destaques',
    highlights: 'Diplomacia\nEmbaixadas\nRelações internacionais',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/mre/',
  },
  {
    emoji: '❤️',
    iconBgColor: '#fee2e2',
    accentColor: '#dc2626',
    title: 'Ministério da Saúde',
    description:
      'Responsável pela política nacional de saúde pública, SUS e vigilância sanitária.',
    themes: 'social, saúde',
    searchKeywords: 'ms, sus, saúde, vacinação',
    highlightsLabel: 'Destaques',
    highlights: 'SUS\nVacinação\nAtenção básica',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/saude/',
  },
  {
    emoji: '📢',
    iconBgColor: '#fef3c7',
    accentColor: '#b45309',
    title: 'Secretaria de Comunicação Social',
    description: 'Coordena a comunicação institucional do governo.',
    highlightsLabel: 'Destaques',
    highlights: 'Campanhas\nImprensa\nComunicação digital',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/secom/',
  },
  {
    emoji: '🧑‍🤝‍🧑',
    iconBgColor: '#ecfccb',
    accentColor: '#65a30d',
    title: 'Secretaria-Geral da Presidência',
    description: 'Articula participação social e diálogo com a sociedade.',
    highlightsLabel: 'Destaques',
    highlights: 'Participação social\nConselhos\nDiálogo',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/secretariageral/',
  },
  {
    emoji: '🏛️',
    iconBgColor: '#e0e7ff',
    accentColor: '#3730a3',
    title: 'Secretaria de Relações Institucionais',
    description: 'Coordena relações com o Congresso e entes federativos.',
    highlightsLabel: 'Destaques',
    highlights:
      'Articulação política\nGovernabilidade\nRelações institucionais',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/sri/',
  },
  {
    emoji: '🚛',
    iconBgColor: '#f1f5f9',
    accentColor: '#334155',
    title: 'Ministério dos Transportes',
    description: 'Responsável pela infraestrutura de transportes terrestres.',
    highlightsLabel: 'Destaques',
    highlights: 'Rodovias\nFerrovias\nLogística',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/transportes/',
  },
  {
    emoji: '👷',
    iconBgColor: '#fef3c7',
    accentColor: '#b45309',
    title: 'Ministério do Trabalho e Emprego',
    description: 'Regula relações de trabalho e políticas de emprego.',
    themes: 'social, trabalho',
    searchKeywords: 'mte, carteira de trabalho, emprego',
    highlightsLabel: 'Destaques',
    highlights: 'Carteira de trabalho\nEmprego\nFiscalização',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/trabalho/',
  },
  {
    emoji: '🏖️',
    iconBgColor: '#e0f2fe',
    accentColor: '#0284c7',
    title: 'Ministério do Turismo',
    description: 'Promove o turismo nacional e internacional.',
    highlightsLabel: 'Destaques',
    highlights: 'Destinos\nEventos\nPromoção',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/turismo/',
  },
  {
    emoji: '🐟',
    iconBgColor: '#dcfce7',
    accentColor: '#15803d',
    title: 'Ministério da Pesca e Aquicultura',
    description: 'Desenvolve a pesca e aquicultura.',
    highlightsLabel: 'Destaques',
    highlights: 'Produção pesqueira\nSustentabilidade\nIncentivo',
    buttonLabel: 'Acessar Portal',
    href: 'https://www.gov.br/mpa/',
  },
];
